version: 2
jobs:
  build:
    working_directory: ~/repo # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:10.15.3 # ...with this image as the primary container; this is where all `steps` will run
      - image: mongo:3.4.4 # and this image as the secondary service container
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: "sudo npm install -g npm@latest"
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: "npm install"

      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: install-jest-cli #TODO: Try to cache seperately from  standard dependencies
          command: "sudo npm install -g jest-cli"

      - run:
          name: Run all tests
          command: npm run ci:test

      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: coverage
          prefix: coverage

    deploy:
      - checkout
      - setup_remote_docker:
      - run:
          name: Building and uploading image to DockerHub
          command: npm run ci:docker

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
  # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
